name: Generate Zora Report

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 0,6,12,18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas matplotlib

    - name: Run fetch_and_save_holders.py
      run: python fetch_and_save_holders.py

    - name: Run all_time_holders.py
      run: python all_time_holders.py

    - name: Update README.md with results
      run: |
        total_holders=$(tail -n +2 data.csv | wc -l)
        holders_gt_11=$(awk -F ',' '$2 >= 11' data.csv | wc -l)
        holders_gt_111=$(awk -F ',' '$2 >= 111' data.csv | wc -l)
        mean_balance=$(awk -F ',' '{sum+=$2} END {print sum/NR}' data.csv)
        addresses_held_once=$(tail -n +2 holders.csv | wc -l)
        
        echo "# Zora Report" > README.md
        echo "## Report of bought mints on Zora" >> README.md
        echo "Last updated: $(date -u +"%d-%m-%Y %H:%M")" >> README.md
        echo "Addresses which held mint at least once: $addresses_held_once" >> README.md
        echo "" >> README.md
        echo "## Current holders:" >> README.md
        echo "Holders with >1: $total_holders" >> README.md
        echo "Holders with >=11: $holders_gt_11" >> README.md
        echo "Holders with >=111: $holders_gt_111" >> README.md
        echo "Mean balance: $mean_balance" >> README.md
        echo "" >> README.md
        echo "## Progression Curve - All Holders" >> README.md
        echo "![Progression Curve - All Holders](progression_curve_all.png)" >> README.md
        echo "## Progression Curve - Holders >=11" >> README.md
        echo "![Progression Curve - Holders >=11](progression_curve_gt_11.png)" >> README.md
        echo "## Progression Curve - Holders >=111" >> README.md
        echo "![Progression Curve - Holders >=111](progression_curve_gt_111.png)" >> README.md

    - name: Check for generated files
      run: |
        if [ ! -f progression_curve_all.png ]; then
          echo "progression_curve_all.png does not exist."
          exit 1
        fi
        if [ ! -f progression_curve_gt_11.png ]; then
          echo "progression_curve_gt_11.png does not exist."
          exit 1
        fi
        if [ ! -f progression_curve_gt_111.png ]; then
          echo "progression_curve_gt_111.png does not exist."
          exit 1
        fi
        if [ ! -f progression_data.csv ]; then
          echo "progression_data.csv does not exist."
          exit 1
        fi

    - name: Commit and push results if there are changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md progression_curve_all.png progression_curve_gt_11.png progression_curve_gt_111.png data.csv progression_data.csv
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m 'Update README.md with Zora report and data'
          git push
        else
          echo "No changes to commit"
        fi
